dist: trusty

language: rust

services: docker

sudo: required

cache: cargo

before_cache:
  - chmod -R a+r $HOME/.cargo

notifications:
  email:
    on_success: never

branches:
  only:
    - "/^v\\d+\\.\\d+\\.\\d+.*$/"
    - master
    - develop

before_install:
  - set -e
  - rustup self update

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

after_script: set +e

env:
  global:
    - CRATE_NAME=fcat

matrix:
  include:
    - env: TARGET=aarch64-linux-android DISABLE_TESTS=1
    - env: TARGET=arm-linux-androideabi DISABLE_TESTS=1
    - env: TARGET=armv7-linux-androideabi DISABLE_TESTS=1
    - env: TARGET=i686-linux-android DISABLE_TESTS=1
    - env: TARGET=x86_64-linux-android DISABLE_TESTS=1
    - env: TARGET=aarch64-unknown-linux-gnu
    - env: TARGET=arm-unknown-linux-gnueabi
    - env: TARGET=armv7-unknown-linux-gnueabihf
    - env: TARGET=i686-unknown-linux-gnu
    - env: TARGET=i686-unknown-linux-musl
    - env: TARGET=mips-unknown-linux-gnu
    - env: TARGET=mips64-unknown-linux-gnuabi64
    - env: TARGET=mips64el-unknown-linux-gnuabi64
    - env: TARGET=mipsel-unknown-linux-gnu
    - env: TARGET=powerpc-unknown-linux-gnu
    - env: TARGET=powerpc64-unknown-linux-gnu
    - env: TARGET=powerpc64le-unknown-linux-gnu
    - env: TARGET=s390x-unknown-linux-gnu DISABLE_TESTS=1
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-musl

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  api_key:
    secure: "B+uNhblkxY3VfIKrH5TSthtaTxisAmK8ZoSasI+LuAwqbo+yEOri8CEhvC2jdsedYmPk4k1fjjygIyr2SveKeT/ZPv3OlArAqjaos8Kd7YNauh4V6p+BNcstH9Gs6ZiyC6cQxJduJYI3zeyMZ5oOc4xlcKoKCq3aXa4CIwOtREZX9ENOuiHY2oeiJ7CkBt5sXIwbAISxjNYESr6lYA9e/N7i+R5r89iKe23eAxaYtr1YnhxmK4eByIq2afPiilj/v6SZmSrQ6rYtOmDNI62Uwr0l2QnSJA1UtNJF/uqUj1QlLhN29PmPUaxysHlKoIZmPCLf3PkcNMHt2fxDN+rT0yUFFEBA+OsCihv/T2ZSf4cinUMZiJQsCNThLdpH0RQEWzax3HyIOpQDtYSD0MChf0uIcXwrmWlfYZpcyB/98nzRUg9fro+oPwjoiBCPMH2ZHIag+kFev69uKgv/kE7eho1AbWaA2uzJF05rNsPSlOfgFzFDZJMWWXaS4k8SJvpKF/VNXkdbYnWdf+76c42AhfmUBnDzBJsZWOzt44NikApatJWmBf6GtbNAk1xH7X3HtNfA5jKHQD2v4oo9oU9QNzvxg9QeWv0ze/64+9GuzaASK8yG/iICuQrhhOmaC8wi4q1dWT5JEnrhvrFdQmFvFo2Ht3WKKVcvbkDInQaIlFk="
  provider: releases
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  skip_cleanup: true
  on:
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
